# Generated by Django 4.2.16 on 2024-10-10 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usercontactapplication_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='app.course'),
        ),
    ]
