# Generated by Django 4.2.16 on 2024-10-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_forwhom_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulinfo',
            name='course_modul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='app.coursemodul'),
        ),
    ]
