# Generated by Django 4.2.16 on 2024-10-10 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_modulinfo_course_modul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorworkplace',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace', to='app.mentor'),
        ),
    ]
