# Generated by Django 4.2.16 on 2024-10-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_mentorworkplace_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorworkplace',
            old_name='mentor',
            new_name='mentor_work',
        ),
    ]
